// Need to refactor to hash table
export enum stack {
  ENTERPRISE_LAYER = 0,
  TECHNOLOGY_LAYER = 1,
  PERSONAL_LAYER = 2,
  GOVERNANCE_CHANNEL = 0,
  FINANCE_CHANNEL = 1,
  MARKETING_CHANNEL = 2,
  PRODUCTION_CHANNEL = 3,
  GENESIS_EPIC = 0,
  KNOWLEDGE_EPIC = 1,
  PORTFOLIO_EPIC = 2,
  COMMUNICATION_EPIC = 3,
  SALES_EPIC = 4
};